const sampleJson = [
    {
      label: "Name",
      placeholder: "John Doe",
      type: "text",
      id: "name-input",
      required: true,
      inputClass: "w-[300px]",
      color: "text-purple",
      textArea: false,
    },
    {
      label: "Age",
      placeholder: "21",
      type: "number",
      id: "age-input",
      required: true,
      inputClass: "py-2 max-w-[100px]",
      color: "text-purple",
      textArea: false,
    },
    {
      label: "Address",
      placeholder: "John Doe",
      id: "address-input",
      required: false,
      inputClass: "py-2 max-w-[300px]",
      labelClass: "text-purple",
      textArea: true,
    },
    {
      label: "Email",
      placeholder: "johndoe@gmail.com",
      type: "email",
      id: "email-input",
      required: true,
      inputClass: "py-2",
      color: "text-purple",
    },
    {
      label: "Password",
      placeholder: "Password",
      type: "password",
      id: "password-input",
      required: true,
      inputClass: "py-2",
      color: "text-purple",
    },
    {
      label: "D.O.B",
      placeholder: "",
      type: "date",
      id: "date-input",
      required: true,
      inputClass: "py-2",
      color: "text-purple",
      errorText: "Invalid Date",
    },
    {
      label: "I agree to the Terms and Conditions.",
      type: "checkbox",
      id: "terms-checkbox",
      required: false,
      inputClass: "py-2 !order-0",
      labelClass: "!order-1",
      outerClass: "!mt-4",
    },
  ];
export default sampleJson;  